apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: training
  name: storage-persistence-volume-claim
spec:
  resources:
    requests:
      storage: 5G
  accessModes:
    - ReadWriteOnce
  storageClassName: fast

