apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-server-rs
spec:
  replicas: 5
  selector:
    #matchLabels:
    #  app: echo-server
    matchExpressions:
      - key: app
        values:
          - echo-server
        operator: In # (In, Notin, Exists)
  template:
    metadata:
      name: echo-server
      labels:
        app: echo-server
        version: v1
        env: production
    spec:
      containers:
        - name: echo-server
          image: landrzejewski/echo-server:v1
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 3
 
