apiVersion: v1
kind: ReplicationController
metadata:
  name: echo-server-rc
spec:
  replicas: 5
  selector:
    app: echo-server
  template:
    metadata:
      name: echo-server
      labels:
        app: echo-server
        version: v1
        env: production
    spec:
      containers:
        - name: echo-server
          image: landrzejewski/echo-server-unhealthy:v1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 3
 
