apiVersion: batch/v1
kind: Job
metadata:
  name: long-task-job
spec:
  completions: 3
  parallelism: 2
  ttlSecondsAfterFinished: 30
  activeDeadlineSeconds: 3600
  template:
   spec:
      restartPolicy: OnFailure
      containers:
        - name: long-task
          image: landrzejewski/long-task:v1

