apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: training
  name: echo-server-replica-set
spec:
  replicas: 10
  selector:
    matchExpressions:
      - key: app-name
        values:
          - echo-server
          - echo
        operator: In
#    matchLabels:
#      app-name: echo-server
  template:
    metadata:
      labels:
        app-name: echo-server
    spec:
      containers:
        - name: echo-server
          image: landrzejewski/echo-server:v1
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: 64M
            limits:
              memory: 128M
