apiVersion: v1
kind: ReplicationController
metadata:
  namespace: training
  name: echo-server-replication-controller
spec:
  replicas: 10
  selector:
    app-name: echo-server
  template:
    metadata:
      labels:
        app-name: echo-server
    spec:
      containers:
        - name: echo-server
          image: landrzejewski/echo-server:v1
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: 64M
            limits:
              memory: 128M
