apiVersion: v1
kind: Service
metadata:
  namespace: training
  name: echo-service
spec:
  selector:
    app-name: echo-server
  #type: ClusterIP #default
  #clusterIP: 17.122.123.11
  ports:
    - port: 80
      targetPort: http #8080
