apiVersion: v1
kind: Service
metadata:
  namespace: training
  name: echo-service
spec:
  selector:
    app-name: echo-server
  type: LoadBalancer
  #clusterIP: 17.122.123.11
  #externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: http #8080
      nodePort: 30000
